export const ADD="ADD"
export const REDUCE="REDUCE"


//abhisek todo with redux

export const GET_TODOS_REQUEST="GET_TODOS_REQUEST"
export const GET_TODOS_SUCCESS="GET_TODOS_SUCCESS"
export const GET_TODOS_ERROR="GET_TODOS_ERROR"


export const POST_TODOS_REQUEST="POST_TODOS_REQUEST"
export const POST_TODOS_SUCCESS="POST_TODOS_SUCCESS"
export const POST_TODOS_ERROR="POST_TODOS_ERROR"

export const DELETE_TODOS_REQUEST="DELETE_TODOS_REQUEST"
export const DELETE_TODOS_SUCCESS="DELETE_TODOS_SUCCESS"
export const DELETE_TODOS_ERROR="DELETE_TODOS_ERROR"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";






